### ISSUE TITLE
Verify Host Based Replication.

### ISSUE THREAD

**Issue by rajat-soda** [sodafoundation/dock#46]
**Issue/Feature Description:**

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by rajat-soda** [comment]
- Setup DRBD between to nodes
- Perform Replication using SODA Dashboard. 
-

**Comment by kumarashit** [comment]
* Test with API (cURL/Postman)

**Comment by kumarashit** [comment]
Closing as the Setup was done and Testing done. From the testing, issues faced and there is another task opened for this. Will follow further progress there
