### ISSUE TITLE
Integrate Github Actions in SODA Projects

### ISSUE THREAD

**Issue by ryo-osive** [sodafoundation/dock#79]
**Issue/Feature Description:**
Integration of Github Actions to SODA Projects
**Why this issue to fixed / feature is needed(give scenarios or use cases):**
This enables you to include Continues Integration (CI) and continuous deployment (CD) capabilities and many other features directly in the repository.

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by kumarashit** [comment]
Done
